<?php
include_once('OAuth.php');

//----------------------------------------------------
include 'connect.php';
if(isset($_COOKIE['cart']))
{
$tbl=$_COOKIE['cart'];

mysql_connect("$host", "$user", "$pass") or die (mysql_error());	
	mysql_select_db("$db") or die(mysql_error());
	
	$items=mysql_query("select * from $tbl");
	
	while($rows=mysql_fetch_array($items))
	{
	$item_no=$rows['itemnumber'];
	$item_name=$rows['itemname'];
	$quantity=$rows['quantity'];
	$cost=$rows['cost'];
			

$fname=mysql_real_escape_string($_POST['first_name']);
$lname=mysql_real_escape_string($_POST['last_name']);
$address=mysql_real_escape_string($_POST['address']);
$phone=mysql_real_escape_string($_POST['phone']);
$email=mysql_real_escape_string($_POST['email']);

$strSQL = "INSERT INTO `iorders` (
`item_no` ,
`item_name` ,
`quantity` ,
`price` ,
`buyer_contacts` 

)
VALUES (
'".$item_no."', '".$item_name."', '".$quantity."', '".$cost."', '".$fname." ".$lname."<BR>ADDRESS: ".$address."<BR>PHONE: ".$phone."<BR>EMAIL: ".$email."'
)";



mysql_query($strSQL) or die (mysql_error());

	}
	
	
	setcookie("cart",$tbl, time()-1);
}
//------------------------------------------------------




//pesapal params
$token = $params = NULL;

/*
Current value for consumer key and consumer secret setup are for the test demo merchant account.
Change this to on live site to appropriate merchant details.
*/
$consumer_key = 'LKA+3RpZeIfk03KmIi96uVwwR7tW2SaM';//demo merchant key
$consumer_secret = '1Xftrz3wyYAi6JdW59Iq6USqPBc=';//demo merchant secret
$signature_method = new OAuthSignatureMethod_HMAC_SHA1();
$iframelink = 'demo.pesapal.com/api/PostPesapalDirectOrderV4';

//get form details
$amount = $_POST['amount'];
$amount = number_format($amount, 2);//format amount to 2 decimal places

$desc = $_POST['description'];
$type = $_POST['type']; //default value = MERCHANT
$reference = $_POST['reference'];//unique order id of the transaction, generated by merchant
$first_name = $_POST['first_name'];
$last_name = $_POST['last_name'];
$email = $_POST['email'];
$username = $email; //same as email

$phonenumber = '';//leave blank
$payment_method = '';//leave blank
$code = '';//leave blank

$callback_url = 'http://localhost.electronics/index.php'; //redirect url, the page that will handle the response from pesapal.

$post_xml = "<?xml version=\"1.0\" encoding=\"utf-8\"?><PesapalDirectOrderInfo xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" Amount=\"".$amount."\" Description=\"".$desc."\" Code=\"".$code."\" Type=\"".$type."\" PaymentMethod=\"".$payment_method."\" Reference=\"".$reference."\" FirstName=\"".$first_name."\" LastName=\"".$last_name."\" Email=\"".$email."\" PhoneNumber=\"".$phonenumber."\" UserName=\"".$username."\" xmlns=\"http://www.pesapal.com\" />";
$post_xml = htmlentities($post_xml);

$consumer = new OAuthConsumer($consumer_key, $consumer_secret);

//post transaction to pesapal
$iframe_src = OAuthRequest::from_consumer_and_token($consumer, $token, "GET", $iframelink, $params);
$iframe_src->set_parameter("oauth_callback", $callback_url);
$iframe_src->set_parameter("pesapal_request_data", $post_xml);
$iframe_src->sign_request($signature_method, $consumer, $token);

//display pesapal - iframe and pass iframe_src
?>
<iframe src="<?php echo $iframe_src;?>" width="100%" height="620px"  scrolling="no" frameBorder="0">
	<p>Browser unable to load iFrame</p>
</iframe>
